version: '3.9'
services:
  app:
    restart: always
    build:
      context: ./client
      target: production
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - node
  web:
    restart: always
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - nodemodulesClient:/app/node_modules
    networks:
      - backend
    depends_on:
      - node
    
  node:
    restart: always
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - nodemodules:/app/node_modules
    networks:
      database:
      backend:
        aliases:
          - 'backend'

    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      database:
        aliases:
          - mongo

volumes:
  mongodb:
  nodemodules: {}
  nodemodulesClient: {}
networks:
  database:
  backend: