version: '3.9'
services:
  node:
    restart: always
    build: .
    env_file:
     - ./.env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    networks:
      - database
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      database:
        aliases:
          - mongo

volumes:
  mongodb:
  nodemodules: {}
networks:
  database: